### ISSUE TITLE
The Dependencies folder is missing

### ISSUE THREAD

**Issue by zeejuncode** [pexavc/LaMarque#1]
The Dependencies folder is missing

**Comment by pexavc** [comment]
@zeejuncode

Which dependencies folder is missing for you? Is it something here?

![Screenshot 2023-12-04 at 3 37 57 PM](https://github.com/pexavc/LaMarque/assets/89366826/e8140839-508d-417b-bded-b4f8d5098c93)

**Comment by pexavc** [comment]
@zeejuncode ah, gitignore issue fixed in latest push on `main`

**Comment by zeejuncode** [comment]
that worked. thanks!
